# Generated by Django 5.1.7 on 2026-03-17 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bons', '0001_initial'),
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(help_text='Calendar year, e.g. 2026')),
                ('label', models.CharField(blank=True, help_text='Display label, auto-generated if blank', max_length=50)),
                ('annual_budget_total', models.DecimalField(decimal_places=2, default=0, help_text='Total maintenance budget for the year', max_digits=12)),
                ('snow_budget', models.DecimalField(decimal_places=2, default=0, help_text='Separate snow removal budget', max_digits=12)),
                ('imprevues_rate', models.DecimalField(decimal_places=4, default=0.15, help_text='Contingency rate, default 15%', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_years', to='houses.house')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SubBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trace_code', models.PositiveIntegerField(help_text='Numeric code (0-99) used to link expenses to this sub-budget')),
                ('name', models.CharField(max_length=150)),
                ('repeat_type', models.CharField(choices=[('annual', 'Annual'), ('unique', 'Unique')], default='annual', max_length=10)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_contingency', models.BooleanField(default=False, help_text='True only for trace_code 0 (Imprévues)')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('budget_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_budgets', to='budget.budgetyear')),
            ],
            options={
                'ordering': ['budget_year', 'sort_order', 'trace_code'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_date', models.DateField(help_text='Date of the expense')),
                ('description', models.CharField(max_length=255)),
                ('bon_number', models.CharField(blank=True, help_text='Legacy pre-printed number or new HHYYNNNN format', max_length=20)),
                ('validated_gl', models.BooleanField(default=False, help_text="Confirmed in the accountant's general ledger")),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('spent_by_label', models.CharField(help_text="e.g. '202 / Marylin' or 'BB' or supplier name", max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_type', models.CharField(choices=[('bon_de_commande', 'Bon de commande'), ('accountant_direct', 'Accountant direct expense'), ('gl_import', 'GL import')], default='bon_de_commande', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('bon_de_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='bons.bondecommande')),
                ('budget_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budget.budgetyear')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_expenses', to=settings.AUTH_USER_MODEL)),
                ('sub_budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budget.subbudget')),
            ],
            options={
                'ordering': ['entry_date', 'created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetyear',
            constraint=models.UniqueConstraint(fields=('house', 'year'), name='unique_budget_year_per_house'),
        ),
        migrations.AddConstraint(
            model_name='subbudget',
            constraint=models.UniqueConstraint(fields=('budget_year', 'trace_code'), name='unique_trace_per_budget_year'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['budget_year', 'entry_date'], name='budget_expe_budget__8e1147_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['sub_budget'], name='budget_expe_sub_bud_0169c6_idx'),
        ),
    ]
