# Generated by Django 5.1.7 on 2026-03-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='approved_reimbursement_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='paid_reimbursement_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='budgetyear',
            name='approved_reimbursement_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='budgetyear',
            name='paid_reimbursement_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
