# Generated by Django 5.1.7 on 2026-03-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetyear',
            name='annual_budget_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Budget total d'entretien pour l'année", max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetyear',
            name='imprevues_rate',
            field=models.DecimalField(decimal_places=4, default='0.1500', help_text="Taux d'imprévues, 15 % par défaut", max_digits=5),
        ),
        migrations.AlterField(
            model_name='budgetyear',
            name='label',
            field=models.CharField(blank=True, help_text="Libellé d'affichage, généré automatiquement si vide", max_length=50),
        ),
        migrations.AlterField(
            model_name='budgetyear',
            name='snow_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Budget de déneigement séparé', max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetyear',
            name='year',
            field=models.PositiveIntegerField(help_text='Année civile, ex : 2026'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bon_number',
            field=models.CharField(blank=True, help_text='Numéro pré-imprimé ou format HHYYNNNN', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='entry_date',
            field=models.DateField(help_text='Date de la dépense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='source_type',
            field=models.CharField(choices=[('bon_de_commande', 'Bon de commande'), ('accountant_direct', 'Dépense directe gestionnaire'), ('gl_import', 'Import grand livre')], default='bon_de_commande', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='spent_by_label',
            field=models.CharField(help_text="ex : '202 / Marylin' ou 'BB' ou nom du fournisseur", max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='validated_gl',
            field=models.BooleanField(default=False, help_text='Confirmé dans le grand livre du gestionnaire'),
        ),
        migrations.AlterField(
            model_name='subbudget',
            name='is_contingency',
            field=models.BooleanField(default=False, help_text='Vrai uniquement pour trace_code 0 (Imprévues)'),
        ),
        migrations.AlterField(
            model_name='subbudget',
            name='repeat_type',
            field=models.CharField(choices=[('annual', 'Annuel'), ('unique', 'Unique')], default='annual', max_length=10),
        ),
        migrations.AlterField(
            model_name='subbudget',
            name='trace_code',
            field=models.PositiveIntegerField(help_text='Code numérique (0-99) reliant les dépenses à ce sous-budget'),
        ),
    ]
