# Generated by Django 5.1.7 on 2026-03-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budgetcategory_approved_reimbursement_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='planned_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Planned spend available for transparency and roll-up reporting.', max_digits=12),
        ),
    ]
