# Generated by Django 5.1.7 on 2026-03-22 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_add_sub_budget_to_extracted_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Le montant ne peut pas être négatif.')]),
        ),
    ]
