# Generated by Django 5.1.7 on 2026-03-22 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_cancellation',
            field=models.BooleanField(default=False, help_text="Vrai si cette entrée est une annulation d'une dépense précédente"),
        ),
        migrations.AddField(
            model_name='expense',
            name='reversal_of',
            field=models.ForeignKey(blank=True, help_text='La dépense originale que cette entrée annule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='budget.expense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
