# Generated by Django 5.1.7 on 2026-03-22 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_expense_cancellation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandLivreUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file', models.FileField(upload_to='grand_livre/%Y/')),
                ('account_number', models.CharField(blank=True, help_text='Numéro de compte trouvé, ex : 13-51200', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('parsed', 'Analysé'), ('reconciling', 'Rapprochement en cours'), ('reconciled', 'Rapproché'), ('error', 'Erreur')], default='pending', max_length=15)),
                ('gl_total_debit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gl_total_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gl_solde_fin', models.DecimalField(blank=True, decimal_places=2, help_text='Solde fin from the GL total line', max_digits=12, null=True)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('budget_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_uploads', to='budget.budgetyear')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrandLivreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('period', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('description_raw', models.TextField(blank=True)),
                ('description_clean', models.TextField(blank=True, help_text='AI-rewritten description')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('match_confidence', models.CharField(choices=[('exact', 'Correspondance exacte'), ('probable', 'Correspondance probable'), ('unmatched', 'Non apparié')], default='unmatched', max_length=15)),
                ('match_notes', models.TextField(blank=True)),
                ('extracted_apartment', models.CharField(blank=True, max_length=20)),
                ('extracted_bc_number', models.CharField(blank=True, max_length=30)),
                ('is_validated', models.BooleanField(default=False)),
                ('needs_import', models.BooleanField(default=False, help_text='True for coop worker expenses not yet in our system')),
                ('matched_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_matches', to='budget.expense')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='budget.grandlivreupload')),
            ],
            options={
                'ordering': ['upload', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gl_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grille_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('unmatched_gl_count', models.PositiveIntegerField(default=0)),
                ('missing_from_gl_count', models.PositiveIntegerField(default=0)),
                ('is_balanced', models.BooleanField(default=False)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('ai_analysis', models.TextField(blank=True)),
                ('status_light', models.CharField(default='red', help_text='green, yellow, or red', max_length=10)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='budget.grandlivreupload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
