# Generated by Django 5.1.7 on 2026-03-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_grand_livre_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reimburse_to',
            field=models.CharField(blank=True, default='', help_text='member = rembourser le membre, supplier = rembourser le fournisseur', max_length=10),
        ),
    ]
