# Generated by Django 5.1.7 on 2026-03-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_reimburse_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandlivreupload',
            name='period_end_date',
            field=models.DateField(blank=True, help_text='Date de fin de la période couverte par le GL', null=True),
        ),
    ]
