# Generated by Django 5.1.7 on 2026-03-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_gl_period_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandlivreentry',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Métadonnées JSON issues de l'IA, incluant les scores de confiance par champ pour l'analyse et le rapprochement sémantique."),
        ),
    ]
