# Generated by Django 5.1.7 on 2026-09-13 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_grandlivreentry_ai_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationresult',
            name='adjusted_gl_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reconciliationresult',
            name='adjustment_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='GrandLivreAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_to_subtract', models.DecimalField(decimal_places=2, help_text="Montant soustrait de l'écriture comptable source.", max_digits=12)),
                ('reason', models.TextField()),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_adjustments_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='budget.grandlivreentry')),
            ],
            options={
                'ordering': ['entry_id', 'created_at', 'id'],
                'indexes': [models.Index(fields=['entry', 'archived_at'], name='budget_gran_entry_i_9237f1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_to_subtract__gte', 0)), name='gl_adjustment_amount_nonnegative'), models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('entry',), name='one_active_gl_adjustment_per_entry')],
            },
        ),
    ]
