# Generated by Django 5.1.7 on 2026-09-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_reconciliationresult_adjusted_gl_total_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grandlivreentry',
            constraint=models.UniqueConstraint(fields=('upload', 'row_number'), name='unique_gl_row_per_upload'),
        ),
    ]
