# Generated by Django 5.1.7 on 2026-03-17 21:27

import bons.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptExtractedFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_candidate', models.CharField(blank=True, max_length=200)),
                ('purchase_date_candidate', models.DateField(blank=True, null=True)),
                ('subtotal_candidate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tps_candidate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tvq_candidate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_candidate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_merchant', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('confidence_date', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('confidence_subtotal', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('confidence_tps', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('confidence_tvq', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('confidence_total', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('final_merchant', models.CharField(blank=True, max_length=200)),
                ('final_purchase_date', models.DateField(blank=True, null=True)),
                ('final_subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_tps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_tvq', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'receipt extracted fields',
            },
        ),
        migrations.CreateModel(
            name='ReceiptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(max_length=255, upload_to=bons.models.receipt_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256_checksum', models.CharField(blank=True, max_length=64)),
                ('ocr_status', models.CharField(choices=[('NOT_REQUESTED', 'Not Requested'), ('PENDING', 'Pending'), ('EXTRACTED', 'Extracted'), ('CORRECTED', 'Corrected'), ('FAILED', 'Failed')], default='NOT_REQUESTED', max_length=20)),
                ('ocr_raw_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptOcrResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine_name', models.CharField(help_text="e.g. 'paddleocr', 'tesseract'", max_length=50)),
                ('engine_version', models.CharField(blank=True, max_length=50)),
                ('raw_text', models.TextField()),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('confidence_overall', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='BonDeCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='8-char format: HHYYNNNN (e.g., BB260001)', max_length=8, unique=True)),
                ('purchase_date', models.DateField()),
                ('entered_date', models.DateField(auto_now_add=True)),
                ('short_description', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(blank=True, max_length=200)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('work_or_delivery_location', models.CharField(blank=True, max_length=255)),
                ('claimant_address', models.CharField(blank=True, max_length=255)),
                ('claimant_phone', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tps', models.DecimalField(blank=True, decimal_places=2, help_text='Federal tax (TPS/GST)', max_digits=10, null=True)),
                ('tvq', models.DecimalField(blank=True, decimal_places=2, help_text='Provincial tax (TVQ/QST)', max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('signature_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OCR_PENDING', 'OCR Pending'), ('READY_FOR_REVIEW', 'Ready for Review'), ('READY_FOR_VALIDATION', 'Ready for Validation'), ('VALIDATED', 'Validated by Treasurer'), ('EXPORTED_PDF', 'PDF Exported'), ('EMAILED', 'Emailed to Accountant'), ('REIMBURSED', 'Reimbursed'), ('VOID', 'Void')], default='DRAFT', max_length=25)),
                ('purchaser_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('purchaser_unit_snapshot', models.CharField(blank=True, max_length=50)),
                ('purchaser_phone_snapshot', models.CharField(blank=True, max_length=50)),
                ('approver_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('approver_unit_snapshot', models.CharField(blank=True, max_length=50)),
                ('budget_year_label_snapshot', models.CharField(blank=True, max_length=50)),
                ('sub_budget_name_snapshot', models.CharField(blank=True, max_length=150)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('reimbursed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('historical_member_unmatched', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('approver_apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver_bons', to='members.apartment')),
                ('approver_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_bons', to='members.member')),
            ],
            options={
                'verbose_name': 'bon de commande',
                'verbose_name_plural': 'bons de commande',
                'ordering': ['-purchase_date', '-created_at', '-id'],
            },
        ),
    ]
