# Generated by Django 5.1.7 on 2026-03-17 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bons', '0001_initial'),
        ('budget', '0001_initial'),
        ('houses', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='budget_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_de_commande', to='budget.budgetyear'),
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_de_commande', to='houses.house'),
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='purchaser_apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaser_bons', to='members.apartment'),
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='purchaser_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_bons', to='members.member'),
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='signature_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_verified_bons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='sub_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_de_commande', to='budget.subbudget'),
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_bons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_extractions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptfile',
            name='bon_de_commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_files', to='bons.bondecommande'),
        ),
        migrations.AddField(
            model_name='receiptfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='receipt_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='extracted_fields', to='bons.receiptfile'),
        ),
        migrations.AddField(
            model_name='receiptocrresult',
            name='receipt_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocr_results', to='bons.receiptfile'),
        ),
        migrations.AddIndex(
            model_name='bondecommande',
            index=models.Index(fields=['status', 'purchase_date'], name='bons_bondec_status_c92e83_idx'),
        ),
        migrations.AddIndex(
            model_name='bondecommande',
            index=models.Index(fields=['number'], name='bons_bondec_number_7623c9_idx'),
        ),
        migrations.AddIndex(
            model_name='bondecommande',
            index=models.Index(fields=['house', 'budget_year'], name='bons_bondec_house_i_881795_idx'),
        ),
    ]
