# Generated by Django 5.1.7 on 2026-03-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiptextractedfields',
            options={'verbose_name_plural': 'champs extraits de reçus'},
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='apartment_number_candidate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_apartment_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='number',
            field=models.CharField(help_text='Format 8 car. : HHYYNNNN (ex : BB260001)', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('OCR_PENDING', 'OCR en cours'), ('READY_FOR_REVIEW', 'Prêt pour révision'), ('READY_FOR_VALIDATION', 'Prêt pour validation'), ('VALIDATED', 'Validé'), ('EXPORTED_PDF', 'PDF exporté'), ('EMAILED', 'Envoyé au comptable'), ('REIMBURSED', 'Remboursé'), ('VOID', 'Annulé')], default='DRAFT', max_length=25),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='tps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxe fédérale (TPS)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='tvq',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxe provinciale (TVQ)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receiptfile',
            name='ocr_status',
            field=models.CharField(choices=[('NOT_REQUESTED', 'Non demandé'), ('PENDING', 'En attente'), ('EXTRACTED', 'Extrait'), ('CORRECTED', 'Corrigé'), ('FAILED', 'Échoué')], default='NOT_REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='receiptocrresult',
            name='engine_name',
            field=models.CharField(help_text="ex : 'paddleocr', 'tesseract'", max_length=50),
        ),
    ]
