# Generated by Django 5.1.7 on 2026-03-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0003_add_apartment_number_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptextractedfields',
            name='confidence_date',
        ),
        migrations.RemoveField(
            model_name='receiptextractedfields',
            name='confidence_merchant',
        ),
        migrations.RemoveField(
            model_name='receiptextractedfields',
            name='confidence_subtotal',
        ),
        migrations.RemoveField(
            model_name='receiptextractedfields',
            name='confidence_total',
        ),
        migrations.RemoveField(
            model_name='receiptextractedfields',
            name='confidence_tps',
        ),
        migrations.RemoveField(
            model_name='receiptextractedfields',
            name='confidence_tvq',
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_member_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_merchant_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='member_name_candidate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='merchant_address_candidate',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
