# Generated by Django 5.1.7 on 2026-03-18 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0005_add_merchant_model'),
        ('budget', '0002_add_sub_budget_to_extracted_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptextractedfields',
            name='sub_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_fields', to='budget.subbudget', verbose_name='Sous-budget'),
        ),
    ]
