# Generated by Django 5.1.7 on 2026-03-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0006_add_sub_budget_to_extracted_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='summary_candidate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
