# Generated by Django 5.1.7 on 2026-03-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0007_receiptextractedfields_final_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='is_scan_session',
            field=models.BooleanField(default=False, help_text='True for temporary upload containers (hidden from normal views)'),
        ),
    ]
