# Generated by Django 5.1.7 on 2026-03-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0008_add_is_scan_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='is_paper_bc',
            field=models.BooleanField(default=False, help_text='True if this bon was digitized from a paper bon de commande'),
        ),
        migrations.AddField(
            model_name='bondecommande',
            name='paper_bc_number',
            field=models.CharField(blank=True, help_text='Original number from the paper bon de commande (e.g., 16011)', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='associated_bc_number_candidate',
            field=models.CharField(blank=True, help_text='BC number this invoice is associated with', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='bc_number_candidate',
            field=models.CharField(blank=True, help_text='BC number from paper bon de commande', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='document_type_candidate',
            field=models.CharField(blank=True, help_text='paper_bc, invoice, or receipt', max_length=20),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_associated_bc_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_bc_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_document_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_supplier_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='supplier_address_candidate',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='supplier_name_candidate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bondecommande',
            name='number',
            field=models.CharField(help_text='Format HHYYNNNN (digital) ou numéro papier (ex : 16011)', max_length=20, unique=True),
        ),
    ]
