# Generated by Django 5.1.7 on 2026-03-22 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0009_paper_bc_and_doc_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptextractedfields',
            name='expense_apartment_candidate',
            field=models.CharField(blank=True, help_text='Appartement de la personne ayant effectué la dépense', max_length=10),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='expense_member_name_candidate',
            field=models.CharField(blank=True, help_text='Nom de la personne ayant effectué la dépense (signataire du BC papier)', max_length=200),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_expense_apartment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_expense_member_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
