# Generated by Django 5.1.7 on 2026-03-22 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0010_expense_member_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='GPT confidence score (0.00–1.00) that these are the same purchase', max_digits=4, null=True)),
                ('gpt_comparison_result', models.TextField(blank=True, help_text='Raw GPT response from image comparison')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED_DUPLICATE', 'Doublon confirmé'), ('DISMISSED', 'Rejeté')], default='PENDING', max_length=25)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_file', models.ForeignKey(help_text='The new receipt flagged as a possible duplicate', on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_flags', to='bons.receiptfile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_duplicate_flags', to=settings.AUTH_USER_MODEL)),
                ('suspected_duplicate_receipt', models.ForeignKey(help_text='The existing receipt this may be a duplicate of', on_delete=django.db.models.deletion.PROTECT, related_name='flagged_as_duplicate_of', to='bons.receiptfile')),
            ],
            options={
                'verbose_name': 'signalement de doublon',
                'verbose_name_plural': 'signalements de doublons',
                'indexes': [models.Index(fields=['status'], name='bons_duplic_status_d21c11_idx'), models.Index(fields=['receipt_file'], name='bons_duplic_receipt_1f7fb4_idx')],
            },
        ),
    ]
