# Generated by Django 5.1.7 on 2026-03-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0011_add_duplicate_flag_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_validator_apartment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_validator_member_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='signer_roles_ambiguous_candidate',
            field=models.BooleanField(default=False, help_text='True si les deux signatures sont ambiguës et doivent être validées manuellement'),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='signer_roles_ambiguous_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='validator_apartment_candidate',
            field=models.CharField(blank=True, help_text='Appartement du 2e signataire', max_length=10),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='validator_member_name_candidate',
            field=models.CharField(blank=True, help_text='Nom du 2e signataire qui a validé le BC papier', max_length=200),
        ),
    ]
