# Generated by Django 5.1.7 on 2026-03-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0012_receiptextractedfields_final_validator_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='approver_is_external',
            field=models.BooleanField(default=False, help_text='True when the approver/validator is an external supplier (fournisseur), not a coop member'),
        ),
    ]
