# Generated by Django 5.1.7 on 2026-03-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0013_approver_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='invoice_amounts_unverified',
            field=models.BooleanField(default=False, help_text='True when invoice amounts could not be extracted by OCR; the bon total comes from the paper BC and must be verified manually'),
        ),
    ]
