# Generated by Django 5.1.7 on 2026-03-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0014_invoice_amounts_unverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='untaxed_extra_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourboire, livraison ou autres frais non taxables inclus au total', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_untaxed_extra_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='untaxed_extra_amount_candidate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
