# Generated by Django 5.1.7 on 2026-03-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0015_untaxed_extra_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondecommande',
            name='reimburse_to',
            field=models.CharField(blank=True, choices=[('member', 'Membre'), ('supplier', 'Fournisseur')], default='', help_text='Qui rembourser : le membre ou le fournisseur', max_length=10),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_reimburse_to',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='reimburse_to_candidate',
            field=models.CharField(blank=True, help_text='member or supplier — extracted from paper BC', max_length=10),
        ),
    ]
