# Generated by Django 5.1.7 on 2026-03-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0016_reimburse_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondecommande',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('READY_FOR_REVIEW', 'Prêt pour révision'), ('READY_FOR_VALIDATION', 'Prêt pour validation'), ('VALIDATED', 'Validé'), ('SENT_TO_COOP', 'Envoyé à la Grande Coop'), ('REIMBURSED', 'Remboursé'), ('VOID', 'Annulé')], default='DRAFT', max_length=25),
        ),
    ]
