# Generated by Django 5.1.7 on 2026-03-23 00:55

from django.db import migrations


def migrate_old_statuses(apps, schema_editor):
    BonDeCommande = apps.get_model("bons", "BonDeCommande")
    BonDeCommande.objects.filter(status="EMAILED").update(status="SENT_TO_COOP")
    BonDeCommande.objects.filter(status="OCR_PENDING").update(status="DRAFT")
    BonDeCommande.objects.filter(status="EXPORTED_PDF").update(status="VALIDATED")


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0017_update_bon_status_choices'),
    ]

    operations = [
        migrations.RunPython(migrate_old_statuses, migrations.RunPython.noop),
    ]
