# Generated by Django 5.1.7 on 2026-03-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bons', '0018_migrate_old_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicateflag',
            name='field_confidence_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Scores de confiance IA 0-9 ou NA pour les champs JSON de comparaison GPT.'),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='candidate_confidence_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Scores de confiance IA 0-9 ou NA pour les champs candidats extraits.'),
        ),
        migrations.AddField(
            model_name='receiptextractedfields',
            name='final_confidence_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Scores de confiance IA affichables pour les valeurs finales confirmées.'),
        ),
    ]
