# Generated by Django 5.1.7 on 2026-03-17 03:26

import django.db.models.deletion
import reimbursements.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When set, the record has been archived and should stay read-only.', null=True)),
                ('archive_reason', models.CharField(blank=True, help_text='Optional human-readable reason explaining why the record was archived.', max_length=255)),
                ('reference_code', models.CharField(default=reimbursements.models.generate_reimbursement_reference, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('expense_date', models.DateField()),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('void', 'Void')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('member_name_snapshot', models.CharField(max_length=255)),
                ('member_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('apartment_code_snapshot', models.CharField(blank=True, max_length=50)),
                ('apartment_display_snapshot', models.CharField(blank=True, max_length=255)),
                ('residency_start_snapshot', models.DateField(blank=True, null=True)),
                ('residency_end_snapshot', models.DateField(blank=True, null=True)),
                ('budget_year_label_snapshot', models.CharField(max_length=50)),
                ('budget_category_code_snapshot', models.CharField(max_length=50)),
                ('budget_category_name_snapshot', models.CharField(max_length=150)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements', to='members.apartment')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('budget_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements', to='budget.budgetcategory')),
                ('budget_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements', to='budget.budgetyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_reimbursements', to=settings.AUTH_USER_MODEL)),
                ('requested_by_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursements', to='members.member')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When set, the record has been archived and should stay read-only.', null=True)),
                ('archive_reason', models.CharField(blank=True, help_text='Optional human-readable reason explaining why the record was archived.', max_length=255)),
                ('file', models.FileField(max_length=255, upload_to=reimbursements.models.receipt_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sha256_checksum', models.CharField(blank=True, max_length=64)),
                ('ocr_status', models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('extracted', 'Extracted'), ('corrected', 'Corrected'), ('failed', 'Failed')], default='not_requested', max_length=20)),
                ('ocr_raw_text', models.TextField(blank=True)),
                ('ocr_corrected_fields', models.JSONField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipt_files', to=settings.AUTH_USER_MODEL)),
                ('reimbursement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_files', to='reimbursements.reimbursement')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='reimbursement',
            index=models.Index(fields=['status', 'expense_date'], name='reimburseme_status_9ca99b_idx'),
        ),
        migrations.AddIndex(
            model_name='reimbursement',
            index=models.Index(fields=['reference_code'], name='reimburseme_referen_60a617_idx'),
        ),
    ]
