# Generated by Django 5.1.7 on 2026-03-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="2-character alphanumeric house code, e.g. 'BB'", max_length=2, unique=True)),
                ('name', models.CharField(help_text="e.g. 'Maison BB'", max_length=150)),
                ('account_number', models.CharField(help_text="7-char coop account number, e.g. '13-51200'", max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
