# Generated by Django 5.1.7 on 2026-03-18 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='correspondent_member',
            field=models.ForeignKey(blank=True, help_text='Membre correspondant de cette maison', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondent_of_houses', to='members.member'),
        ),
        migrations.AddField(
            model_name='house',
            name='treasurer_member',
            field=models.ForeignKey(blank=True, help_text='Membre trésorier de cette maison', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_of_houses', to='members.member'),
        ),
    ]
