# Generated by Django 5.1.7 on 2026-03-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_correspondent_member_house_treasurer_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='account_number',
            field=models.CharField(help_text="Numéro de compte coop à 7 car., ex : '13-51200'", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='code',
            field=models.CharField(help_text="Code de 2 caractères alphanumériques, ex : 'BB'", max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(help_text="ex : 'Maison BB'", max_length=150),
        ),
    ]
