# Generated by Django 5.1.7 on 2026-03-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_alter_house_account_number_alter_house_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="accounting_code",
            field=models.CharField(
                blank=True,
                help_text="Code comptable court du tableau coop, ex : '13'",
                max_length=10,
            ),
        ),
    ]
