# Generated by Django 5.1.7 on 2026-03-19 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('houses', '0003_alter_house_account_number_alter_house_code_and_more'),
        ('members', '0003_alter_residency_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house',
            field=models.ForeignKey(blank=True, help_text='Required for VIEWER/TREASURER/ADMIN. Null for GESTIONNAIRE.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='houses.house'),
        ),
        migrations.AlterField(
            model_name='user',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Lien optionnel vers la fiche membre de cet utilisateur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='members.member'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Lecteur'), ('TREASURER', 'Trésorier'), ('ADMIN', 'Administrateur'), ('GESTIONNAIRE', 'Gestionnaire')], default='VIEWER', max_length=20),
        ),
    ]
