# Generated by Django 5.1.7 on 2026-03-17 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_role_snapshot', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('target_app_label', models.CharField(max_length=100)),
                ('target_model', models.CharField(max_length=100)),
                ('target_object_id', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_app_label', 'target_model', 'target_object_id'], name='audits_audi_target__56cad8_idx'), models.Index(fields=['created_at'], name='audits_audi_created_262fbf_idx')],
            },
        ),
    ]
