# Generated by Django 5.1.7 on 2026-03-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(help_text="ex : 'bon.validated', 'expense.created'", max_length=100),
        ),
    ]
