# Generated by Django 5.1.7 on 2026-03-17 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment_label_snapshot', models.CharField(blank=True, max_length=50)),
                ('maintenance_item', models.TextField(help_text='Description of work needed')),
                ('responsible_party', models.CharField(help_text="e.g. 'CHCE', 'Interne', 'Membre'", max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('DEFERRED', 'Deferred')], default='OPEN', max_length=20)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_items', to='members.apartment')),
                ('budget_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_items', to='budget.budgetyear')),
                ('linked_sub_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_items', to='budget.subbudget')),
            ],
            options={
                'ordering': ['budget_year', 'apartment__code', 'id'],
            },
        ),
    ]
