# Generated by Django 5.1.7 on 2026-03-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceplanitem',
            name='maintenance_item',
            field=models.TextField(help_text='Description des travaux nécessaires'),
        ),
        migrations.AlterField(
            model_name='maintenanceplanitem',
            name='responsible_party',
            field=models.CharField(help_text="ex : 'CHCE', 'Interne', 'Membre'", max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenanceplanitem',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Ouvert'), ('PLANNED', 'Planifié'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Terminé'), ('DEFERRED', 'Reporté')], default='OPEN', max_length=20),
        ),
    ]
