# Generated by Django 5.1.7 on 2026-03-17 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Unit identifier within the house, e.g. '101', '202', 'BB'", max_length=10)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='houses.house')),
            ],
            options={
                'ordering': ['house__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Residency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residencies', to='members.apartment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residencies', to='members.member')),
            ],
            options={
                'verbose_name_plural': 'residencies',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='apartment',
            constraint=models.UniqueConstraint(fields=('house', 'code'), name='unique_apartment_per_house'),
        ),
        migrations.AddIndex(
            model_name='residency',
            index=models.Index(fields=['member', 'start_date', 'end_date'], name='members_res_member__b315dd_idx'),
        ),
        migrations.AddIndex(
            model_name='residency',
            index=models.Index(fields=['apartment', 'start_date', 'end_date'], name='members_res_apartme_f51907_idx'),
        ),
        migrations.AddConstraint(
            model_name='residency',
            constraint=models.UniqueConstraint(fields=('member', 'apartment', 'start_date'), name='unique_residency_start'),
        ),
    ]
