# Generated by Django 5.1.7 on 2026-03-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residency',
            options={'ordering': ['-start_date', '-id'], 'verbose_name_plural': 'résidences'},
        ),
        migrations.AddField(
            model_name='residency',
            name='is_coop_member',
            field=models.BooleanField(default=True, help_text="Si décoché, la personne habite encore l'appartement mais n'est plus membre de la coop."),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='code',
            field=models.CharField(help_text="Identifiant de l'unité dans la maison, ex : '101', '202', 'BB'", max_length=10),
        ),
    ]
