# Generated by Django 5.1.7 on 2026-03-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_residency_options_residency_is_coop_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residency',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
